# Generated by Django 4.2.27 on 2025-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('prompt', models.TextField(help_text='Промт для генерации контента открытки', verbose_name='Заготовленный промт')),
                ('image', models.ImageField(help_text='Загрузите изображение шаблона', upload_to='card_templates/', verbose_name='Изображение шаблона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
        ),
    ]
