# Generated by Django 4.2.27 on 2025-12-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgG', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtemplate',
            name='image',
        ),
    ]
